### ISSUE TITLE
[BUG] in Create new vehicle type with empty value on data

### ISSUE THREAD

**Issue by eltodoan** [ProjectBengcall/API-Testing#3]
(/admin/vehicle)
User able to create new vehicle type while request value in empty 
The actual result is 201 Created. It should be 400 Bad request or 404 Not found. 
Please fix. Thanks

![Image](https://user-images.githubusercontent.com/105261814/200466470-1520e363-641b-401a-879a-aecb3a974704.jpg)

**Comment by LukmanulKhakim** [comment]
sudah bisa dicoba lagi mas

**Comment by eltodoan** [comment]
done mas. terima kasih
