### ISSUE TITLE
[BUG] Delete vehicle type on admin with invalid id using special character

### ISSUE THREAD

**Issue by eltodoan** [ProjectBengcall/API-Testing#6]
/admin/vehicle/
Admin able to delete vehicle while id on path is not integer but string (Admin change id into character in path). Status code result was 202 Accepted. The response code should be 400 bad request because string is not acceptable in id path (id must be number) and response body value message must match either. Please fix and review. Terima kasih ✌️

![Image](https://user-images.githubusercontent.com/105261814/200762275-d6fe2e24-184b-44a9-b756-df17a608e27a.jpg)

**Comment by LukmanulKhakim** [comment]
sudah bisa dicoba lagi

**Comment by eltodoan** [comment]
@LukmanulKhakim Done mas. Terima kasih
